# Generated by Django 5.0.4 on 2024-04-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_apellido_persona_user_cedula_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Apellido_persona',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Nombre_persona',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
